; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
; Community fork of the original PlatformIO platform-espressif32:
; this gives us full C++26 support (to the extent supported by gcc)
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
    -std=c++26
    -Wall
    -D UNITY_SUPPORT_64
monitor_filters = esp32_exception_decoder
lib_deps =
    h2zero/NimBLE-Arduino@^2.1.0


; No optimizations, debug symbols, debug logs, etc.
[env:debug]
build_type = debug
build_flags =
    -D DEBUG=1
    -D _GLIBCXX_DEBUG=1
debug_build_flags =
    -Og
    -ggdb3
    -g3
debug_init_break =
    tbreak setup
