; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Opzioni comuni
[env]
; Community fork del platform-espressif32 originale (di PlatformIO):
; ci permette di avere il supporto (completo) a C++20/23
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -std=c++23

; Niente ottimizzazioni, simboli di debug, log di debug, ecc.
[debug]
build_type = debug
build_flags =
    -D DEBUG=1
    -D _GLIBCXX_DEBUG=1
debug_build_flags =
    -Og
    -ggdb3
    -g3

; Ottimizzazioni, niente simboli di debug ma log di debug, ecc.
[release]
build_flags =
    -D RELEASE=1
    -D _GLIBCXX_DEBUG=1


; Ottimizzazioni, niente simboli di debug, niente log di debug, ecc.
[production]
build_flags = 
    -D PRODUCTION=1
    -D NDEBUG

[qemu]
board_build.flash_mode = dio
extra_scripts =
    pre:scripts/setup-qemu.py
    post:scripts/merge-firmware.py
    post:scripts/skip-upload.py
debug_tool = custom
debug_port = 1234
debug_server =
    ${PROJECT_DIR}/qemu/qemu/bin/qemu-system-xtensa
    -nographic
    -s
    -S
    -machine
    esp32s3
    -drive
debug_init_break =
    tbreak setup
debug_load_mode = manual
debug_init_cmds =
    define pio_reset_halt_target
        monitor system_reset
    end

    define pio_reset_run_target
        monitor system_reset
    end

    target extended-remote :$DEBUG_PORT
    $LOAD_CMD
    pio_reset_halt_target
    $INIT_BREAK
test_testing_command = 
    ${PROJECT_DIR}/qemu/qemu/bin/qemu-system-xtensa
    -nographic
    -machine
    esp32s3
    -drive

[env:debug]
extends = debug
build_flags = ${env.build_flags} ${debug.build_flags}

[env:release]
extends = release
build_flags = ${env.build_flags} ${release.build_flags}

[env:production]
extends = production
build_flags = ${env.build_flags} ${production.build_flags}

[env:qemu-debug]
extends = qemu, debug
build_flags = ${env.build_flags} ${debug.build_flags}
debug_server =
    ${qemu.debug_server}
    file=${platformio.build_dir}/${this.__env__}/qemu-image.bin,if=mtd,format=raw
test_testing_command =
    ${qemu.test_testing_command}
    file=${platformio.build_dir}/${this.__env__}/qemu-image.bin,if=mtd,format=raw

[env:qemu-release]
extends = qemu, release
build_flags = ${env.build_flags} ${release.build_flags}
debug_server =
    ${qemu.debug_server}
    file=${platformio.build_dir}/${this.__env__}/qemu-image.bin,if=mtd,format=raw
test_testing_command =
    ${qemu.test_testing_command}
    file=${platformio.build_dir}/${this.__env__}/qemu-image.bin,if=mtd,format=raw

[env:qemu-production]
extends = qemu, production
build_flags = ${env.build_flags} ${production.build_flags}
debug_server =
    ${qemu.debug_server}
    file=${platformio.build_dir}/${this.__env__}/qemu-image.bin,if=mtd,format=raw
test_testing_command =
    ${qemu.test_testing_command}
    file=${platformio.build_dir}/${this.__env__}/qemu-image.bin,if=mtd,format=raw