; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --- AMBIENTE DI VOLO (Microcontrollore) ---
[env:esp32s3_flight]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<*> -<../sim/>

; --- AMBIENTE DI SIMULAZIONE (Desktop PC) ---
[env:simulatore_pc]
platform = native
build_src_filter = +<../sim/> -<*>