name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pio-test:
    name: PlatformIO Test App
    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.number }}
      GREEN: '\033[1;32m'
      YELLOW: '\033[1;33m'
      RED: '\033[1;31m'
      DONE: '\033[0m'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Cache PlatformIO deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ${{ github.workspace }}/app/.pio
          key: pio-app-v1-${{ hashFiles( 'app/platformio.ini', 'app/lib/**/*', 'app/src/**/*', 'app/include/**/*' ) }}
          restore-keys: |
            pio-app-

      - name: Cache PlatformIO tests
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/app/.pio/build/**/test
            ${{ github.workspace }}/app/.pio/build/**/unity_config_build
            ${{ github.workspace }}/app/.pio/build/**/Unity
          key: pio-test-v1-${{ hashFiles( 'app/platformio.ini', 'app/test/**/*' ) }}
          restore-keys: |
            pio-test-

      # Cache SDL2 library: needed for QEMU
      - name: Cache SDL2 lib
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libsdl2-2.0-0
          version: 1.0

      - name: Cache QEMU
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/app/qemu
          key: qemu-app-v1-${{ hashFiles( 'app/qemu/.version' ) }}
          restore-keys: |
            qemu-app-
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run app tests using pio
        run: |
          echo -e "$YELLOW[Info]: Running app tests...$DONE"
          pio test -vv -d "${{ github.workspace }}/app" -e qemu-debug -e qemu-release -e qemu-production || {
            echo -e "$RED[Error]: Test failed for app$DONE"
            exit 1
          }
          echo -e "$GREEN[Success]: App tests passed successfully!$DONE"

      - name: "App tests failure: comment on PR"
        if: ${{ failure() && github.event_name == 'pull_request' }}
        run: gh pr comment $PR_NUMBER --body "Error, tests failed for \`app\`. Please check the logs for details."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
